version: "3.9"
services:
  babylon-staking-indexer:
    image: babylonlabs-io/babylon-staking-indexer:latest
    container_name: babylon-staking-indexer
    environment:
      - CONFIG=/home/babylon-staking-indexer/config.yml
    depends_on:
      - indexer-mongodb
      - rabbitmq
    volumes:
      - ./config/config-docker.yml:/home/babylon-staking-indexer/config.yml:Z
  indexer-mongodb:
    image: mongo:latest
    container_name: indexer-mongodb
    hostname: indexer-mongodb
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./bin/init-mongo.sh:/init-mongo.sh
    entrypoint: [ "/init-mongo.sh" ]
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
